### ISSUE TITLE
Csound WASM: 'float unrepresentable in integer range' error

### ISSUE THREAD

**Issue by stekyne** [csound/csound#1050]
Scenario: Using setChannel, send a value to the Csound wasm backend. Depending on the datatype/value, it might throw an error like:

Uncaught RuntimeError: float unrepresentable in integer range
   at _early_process (wasm-function[2167]:2797)
   at _kperf_nodebug (wasm-function[261]:789)
   at dynCall_ii (wasm-function[4445]:12)
   at invoke_ii (http://localhost:3000/csound-wasm/libcsound-worklet.js:8748:32)
   at _csoundPerformKsmps (wasm-function[274]:647)
   at _CsoundObj_performKsmps (wasm-function[132]:31)
   at AudioWorkletProcessor.process (http://localhost:3000/csound-wasm/CsoundProcessor.js:149:33)

This was generated by accidentally passing in a NAN. It might occur with a denormal value also. 

https://kripken.github.io/emscripten-site/docs/compiling/WebAssembly.html#trap-mode This section describes the behavior, it is possible to compile via emscripten using a different method, clamp. This will prevent the error but result in slightly slower code.

**Comment by hlolli** [comment]
I wonder if the clamp mode causes some performance loss. I had this error too recently, with foscil, and I was passing NaN too I think. I imagine this clamp to be some js code inside the emscripten bundle, so I can't imagine that slowing down anything.

**Comment by vlazzarini** [comment]
I guess we can try and see. Since this is a build issue, we could provide separate packages with trap and clamp, and let the user decide which to use.
