### ISSUE TITLE
Segmentation fault when a csoundMessageStringCallback is configured and a new performance is started using csoundReset

### ISSUE THREAD

**Issue by neithanmo** [csound/csound#1096]
Hi developers.

I have configured a messageString Callback to my csound instance, the documentation for this callback is as follow:
     "Sets an alternative function to be called by Csound to print an informational message, using a less granular signature. This callback can be set for –realtime mode"

The callbacks works well, but after a first performance I would like to perform another csd file, so I have to call  csoundReset(), but after this I got a segmentation fault:

The backtrace shows:

#0  _IO_vsnprintf (string=0x0, maxlen=<optimized out>, 
    format=0x7ffff7b343d5 "0dBFS level = %.1f\n", args=0x7fffffffdaa8)
    at vsnprintf.c:112
#1  0x00007ffff79119bc in csoundMessage () from /usr/lib/libcsound64.so.6.0
#2  0x00007ffff79156d9 in csoundReset () from /usr/lib/libcsound64.so.6.0
#3  0x0000555555554bc5 in main ()

This not happens when the message callback is disable. I am using the csound c API version 6.12.
I tried to enable the callback again after the reset call but didn't work... the c file is:
[example1_code.txt](https://github.com/csound/csound/files/2728560/example1_code.txt)

and csd file is:

[csd.txt](https://github.com/csound/csound/files/2728558/csd.txt)

**Comment by vlazzarini** [comment]
it may well be a bug, we need to look at it. A short term solution may be to instead destroy the Csound instance and re-instantiate it before enabling the callback again

**Comment by jpffitch** [comment]
Can this be closed?

**Comment by vlazzarini** [comment]
I accepted the PR
