### ISSUE TITLE
turnoff in UDO causes segfault..

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#1305]
It seems calling turnoff in a UDO causes a crash. The following code showcases the problem:

```
<CsoundSynthesizer>
<CsOptions>
-odac
</CsOptions>
<CsInstruments>

ksmps = 32
nchnls = 2
0dbfs = 1

opcode MyUDO,a,0
    kTimer linseg 0, 5, 5
    if(kTimer > 1) then
        turnoff
    endif
    xout a(1)
endop

instr 1
    a1 MyUDO
endin

</CsInstruments>
<CsScore>
i1 0 8
</CsScore>
</CsoundSynthesizer>
```

**Comment by jpffitch** [comment]
Yes
```
158     }
159
160     int32_t turnoff(CSOUND *csound, LINK *p)/* terminate the current instrument  */
161     {                                       /* called by turnoff statmt at Ptime */
162         IGN(csound);
163         INSDS  *lcurip = CS_PDS->insdshead;
164         if (p->h.insdshead->actflg) {
165         /* IV - Oct 16 2002: check for subinstr and user opcode */
166         /* find top level instrument instance */
167           while (lcurip->opcod_iobufs)
(gdb) where
#0  0x00007ffff793eb4b in turnoff (csound=0x626040, p=0x91f780)
    at /home/jpff/csound6/OOps/goto_ops.c:163
#1  0x00007ffff78de4d0 in useropcd2 (csound=0x626040, p=0x87cd60)
    at /home/jpff/csound6/Engine/insert.c:2269
#2  0x00007ffff78c5b52 in kperf_nodebug (csound=0x626040)
    at /home/jpff/csound6/Top/csound.c:1758
#3  0x00007ffff78c75d6 in csoundPerform (csound=0x626040)
    at /home/jpff/csound6/Top/csound.c:2285
#4  0x00000000004015e5 in main (argc=2, argv=0x7fffffffddf8)
    at /home/jpff/csound6/Frontends/csound/csound_main.c:328
```
The value of CS_PDS is null.  Outside my knowledge.

**Comment by kunstmusik** [comment]
I think I have fixed it, but would like additional tests.  Could someone double-check this work?  It didn't make sense to me to go through to insdshead back to pds then back up to insdshead, when we could just look at the first insdshead.  (@jpffitch @vlazzarini @rorywalsh )

**Comment by rorywalsh** [comment]
Thanks Steven. It passes my tests here. Feel free to close this now ;)

**Comment by jpffitch** [comment]
Seems to have a problem -  see #1306

**Comment by kunstmusik** [comment]
Yes, looking at it now.
