### ISSUE TITLE
Csound for Android does not load the layout

### ISSUE THREAD

**Issue by Joed-Paes** [csound/csound#1368]
Hello,

Currently, I'm trying to run a simple example to run a sound file (.csd) using Android Studio. I already build the library csoundAndroid into Android Studio and it seems that build is okay and I did not get any error message. However, when I install the app, the layout does not load (buttons, seekbars does not appear). 

I realize that if I use the standard class definition: "public class MainActivity extends AppCompatActivity {...}" the layout load properly (obs.: I continue using and loading the csound library without errors). However, when I extend the class using BaseCsound Activity like: "public class MainActivity extends BaseCsoundActivity {...}"  I do not have any error, but the layout components does not appear, and the screen stay white. Nevertheless, the app is installed in my cellphone.

Do you have an idea how to fix this problem? The same occur with the example coming with the library and the tutorial inside the PDF csound manual. Currently, I'm using the compile Sdk Version 30 (API 30: Android 10.0+), but I already have tried with versions 22 and 16 and the same problem occurred. Any help is welcome.

Thanks in advance.
Joed

**Comment by vlazzarini** [comment]
Is this a problem with the Csound library or API or an application specific issue that goes beyond it, then this is not the place to ask questions.

Please confirm whether this is an issue with the library or API.

**Comment by kunstmusik** [comment]
@Joed-Paes have you tried modifying BaseCsoundActivity to extend AppCompatActivity? I'm guessing that would work but I haven't looked AppCompatActivity before.

**Comment by Joed-Paes** [comment]
> Is this a problem with the Csound library or API or an application-specific issue that goes beyond it? If the latter is the case, then this is not the place to ask development questions.
> 
> Please confirm whether this is an issue with the library or API.

I think the problem is about the API connection with the activity class, because it is a simple example that work before I extend the activity class to the BaseCsoundActivity. Anyway, I thank you for your help.

**Comment by Joed-Paes** [comment]
> @Joed-Paes have you tried modifying BaseCsoundActivity to extend AppCompatActivity? I'm guessing that would work but I haven't looked AppCompatActivity before.

Hello Steven. I've tried to modify the BaseCsoundActivity class to extend the AppCompatActivity instead of Activity. However, the problem keep the same. The app built without errors and got installed to the cellphone with white screen. I'm using the android Studio 4.0.1.0 on Linux Ubuntu. I have tried many things, maybe can be a version problem. Thank you so much.

**Comment by kunstmusik** [comment]
Odd, I testing on Pixel 3 here and I haven't had issues with the activities.  Do you see any errors reported in LogCat?  Also, what device are you testing on?

**Comment by Joed-Paes** [comment]
> Odd, I testing on Pixel 3 here and I haven't had issues with the activities. Do you see any errors reported in LogCat? Also, what device are you testing on?

I tested it in Pixel 3 too and, unfortunately, got the same behavior. The LogCat reported the following as error. Have you an idea how can I deal with this?

2020-08-17 23:49:48.377 1497-6446/? E/Vision: Error loading module com.google.android.gms.vision.ocr optional module true: vvs: No acceptable module found. Local version is 0 and remote version is 0.
2020-08-17 23:49:48.390 1497-6446/? E/Vision: Error loading module com.google.android.gms.vision.ocr optional module true: vvs: No acceptable module found. Local version is 0 and remote version is 0.
2020-08-17 23:49:53.019 1497-6529/? E/Vision: Error loading module com.google.android.gms.vision.ocr optional module true: vvs: No acceptable module found. Local version is 0 and remote version is 0.
2020-08-17 23:49:53.040 1497-6529/? E/Vision: Error loading module com.google.android.gms.vision.ocr optional module true: vvs: No acceptable module found. Local version is 0 and remote version is 0.
2020-08-17 23:51:12.389 1290-3470/? E/SQLiteDatabase: Error inserting flex_time=1000 extras={"fetchReason":{"6":0},"fetchPackage":{"com.google.android.gm":4}} job_id=-1 period=2000 source=16 requires_charging=0 target_class=com.google.android.gms.phenotype.service.sync.PhenotypeConfigurator user_id=0 target_package=com.google.android.gms tag=PhenotypeSyncImmediately task_type=0 required_idleness_state=0 service_kind=0 source_version=201817000 required_network_type=0 runtime=1597718852975 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:938)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1701)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1570)
        at apla.a(:com.google.android.gms@201817022@20.18.17 (040700-311416286):78)
        at apkp.a(:com.google.android.gms@201817022@20.18.17 (040700-311416286):196)
        at apkp.a(:com.google.android.gms@201817022@20.18.17 (040700-311416286):20)
        at apkp.c(:com.google.android.gms@201817022@20.18.17 (040700-311416286):9)
        at apkp.a(:com.google.android.gms@201817022@20.18.17 (040700-311416286):98)
        at apkk.handleMessage(:com.google.android.gms@201817022@20.18.17 (040700-311416286):8)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at adxm.a(:com.google.android.gms@201817022@20.18.17 (040700-311416286):2)
        at adxm.dispatchMessage(:com.google.android.gms@201817022@20.18.17 (040700-311416286):14)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2020-08-17 23:51:23.501 1290-6769/? E/SQLiteDatabase: Error inserting flex_time=1000 extras={"fetchReason":{"7":0},"fetchPackage":{"com.google.android.gms.pay":4}} job_id=-1 period=2000 source=16 requires_charging=0 target_class=com.google.android.gms.phenotype.service.sync.PhenotypeConfigurator user_id=0 target_package=com.google.android.gms tag=PhenotypeSyncImmediately task_type=0 required_idleness_state=0 service_kind=0 source_version=201817000 required_network_type=0 runtime=1597719074024 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0
    android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:938)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:88)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1701)
        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1570)
        at apla.a(:com.google.android.gms@201817022@20.18.17 (040700-311416286):78)
        at apkp.a(:com.google.android.gms@201817022@20.18.17 (040700-311416286):196)
        at apkp.a(:com.google.android.gms@201817022@20.18.17 (040700-311416286):20)
        at apkp.c(:com.google.android.gms@201817022@20.18.17 (040700-311416286):9)
        at apkn.run(Unknown Source:2)
        at apkl.a(Unknown Source:19)
        at aphu.run(Unknown Source:0)
        at sji.b(:com.google.android.gms@201817022@20.18.17 (040700-311416286):12)
        at sji.run(:com.google.android.gms@201817022@20.18.17 (040700-311416286):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at spj.run(:com.google.android.gms@201817022@20.18.17 (040700-311416286):0)
        at java.lang.Thread.run(Thread.java:923)
2020-08-17 23:52:12.044 178-183/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup34: Permission denied
2020-08-17 23:52:12.058 178-183/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup35: Permission denied
2020-08-17 23:52:13.561 178-183/? E/android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup34: Permission denied

**Comment by Joed-Paes** [comment]
I solved my problem when I guaranteed the jniLibs (libc++_shared.so, libcsoundandroid.so and libsndfile.so) in the right place in the loaded module of the library. Thank you all for the help.
