### ISSUE TITLE
Calling csoundCompileCsdText causes immediate end of performance

### ISSUE THREAD

**Issue by hlolli** [csound/csound#1420]
This is a bug I encountered while developing wasm, but this is reproducible with the c api.

Int this example, I call start before compiing any orchestra string, and allow it to run for 2 seconds before calling compile. 
With or without deamon enabled,
calling this csd will abruptly end the performance, the result from csound->kperf is -1. Although I can't
see how evaluating this should have an effect on the realtime performance, especially in daemon mode
and especially when there isn't an error in this csd, other than warnings about not being able to set
some constants after start.

```c
#include <stdio.h>
#include <csound/csound.h>


const char* csd = "<CsoundSynthesizer>\n"
  "<CsInstruments>\n"
  "sr=44100\n"
  "ksmps=64\n"
  "0dbfs=1\n\n"
  "instr 1\n"
  "aout vco2 0.1, 440\n"
  "outs aout, aout\n"
  "endin\n"
  "</CsInstruments>\n"
  "<CsScore>\n"
  "i 1 0 1\n"
  "</CsScore>\n"
  "</CsoundSynthesizer>\n"
  ;

int main(int arg, char** argv) {
  void* thread;

  csoundInitialize(CSOUNDINIT_NO_ATEXIT);

  CSOUND* csound = csoundCreate(NULL);

  csoundSetOption(csound, "-odac");
  csoundSetOption(csound, "--daemon");

  csoundStart(csound);
  int kr = csoundGetKr(csound);
  int cnt = 0;
  while (csoundPerformKsmps(csound) == 0) {
    if (cnt == kr*2) {
      csoundCompileCsdText(csound, csd);
    }
    cnt++;
  }
  return 0;
}

```

**Comment by vlazzarini** [comment]
Ok, it's a problem with  ```csoundCompileCsdText()```. I tested with compileOrc and it runs. It seems to be inserting an end of score in the score text.

**Comment by vlazzarini** [comment]
Ok, I think we need @jpffitch  here. There's something possibly in one_file.c stopping the performance. Line 523 says

```
corfile_puts(csound, "\ne\n#exit\n", csound->scorestr);
```

and I am not sure whether that's doing what it says... exiting.

**Comment by giovannibedetti** [comment]
As a side note, we're using it successfully in CsoundUnity (but calling it just once)
https://github.com/rorywalsh/CsoundUnity/blob/8d07aafb93f435989639b297c67a11ec8bb8c9fb/Runtime/CsoundUnityBridge.cs#L95

**Comment by hlolli** [comment]
> As a side note, we're using it successfully in CsoundUnity (but calling it just once and before start)
> https://github.com/rorywalsh/CsoundUnity/blob/8d07aafb93f435989639b297c67a11ec8bb8c9fb/Runtime/CsoundUnityBridge.cs#L95

It works fine when start is called first. In my opinion it's bit silly to compile a csd after start, as all audio constants will get ignored. But it's supposed to work from what I've heard.

**Comment by jpffitch** [comment]
#exit is the tag to the scre pre lexer to end the lexing

**Comment by jpffitch** [comment]
Believed fixed.  Please try

**Comment by kunstmusik** [comment]
I haven't tested @hlolli 's test case, but the latest changes did fix the issue with no CsScore that Victor reported separately with the web-ide. (We'll be deploying that soon hopefully using 6.16.0 code.).

**Comment by hlolli** [comment]
This is fixed, but I think the output device name is now wrong, it says for example project.sco when it should be project.csd. That's unrelated so I'll open a seperate ticket for that.

OTOH running the example there again, I'm not sure if this is a regression or not, but calling CTRL-C throws stacktrace at me

```
0dBFS level = 32768.0
--Csound version 6.15 (double samples) Jan  1 1980
[commit: none]
libsndfile-1.0.30
rtaudio: ALSA module enabled
rtmidi: ALSA Raw MIDI module enabled
graphics suppressed, ascii substituted
0dBFS level = 32768.0
orch now loaded
audio buffered in 256 sample-frame blocks
ALSA: -B 1024 not allowed on this device; using 8192 instead
ALSA output: total buffer size: 8192, period size: 256
writing 256 sample blks of 64-bit floats to dac
SECTION 1:
[W][000013587.748786][remote-node.c:649 client_node_port_use_buffers()] Failed to mlock memory 0x7f4767fc2000 32832: This is not a problem but for best performance, consider increasing RLIMIT_MEMLOCK
STARTING FILE
Creating orchestra
closing tag
Creating score
WARNING: system constants can only be set once

WARNING: system constants can only be set once

WARNING: system constants can only be set once

  rtevent:	   T  2.000 TT  2.000 M:      0.0
new alloc for instr 1:
WARNING: Excess channels ignored

^Cbacktrace() returned 14 addresses
/nix/store/bkg0g0g6adb6gam9yn6bdkigk8lp1mn5-csound-6.15.0/lib/libcsound64.so.6.0(+0x47303) [0x7f476b3a8303]
/nix/store/gafigwfaimlziam6qhw1m8dz4h952g1n-glibc-2.32-35/lib/libc.so.6(+0x3c3a0) [0x7f476b1dc3a0]
/nix/store/gafigwfaimlziam6qhw1m8dz4h952g1n-glibc-2.32-35/lib/libc.so.6(__poll+0x49) [0x7f476b291329]
/nix/store/94ih212nc4nq8dy7vn03vzh9kk7znxk3-alsa-lib-1.2.4/lib/libasound.so.2(+0x58da5) [0x7f476a483da5]
/nix/store/94ih212nc4nq8dy7vn03vzh9kk7znxk3-alsa-lib-1.2.4/lib/libasound.so.2(+0x5e0dd) [0x7f476a4890dd]
/nix/store/94ih212nc4nq8dy7vn03vzh9kk7znxk3-alsa-lib-1.2.4/lib/libasound.so.2(snd_pcm_mmap_writei+0x52) [0x7f476a495552]
/nix/store/94ih212nc4nq8dy7vn03vzh9kk7znxk3-alsa-lib-1.2.4/lib/libasound.so.2(+0xa0b62) [0x7f476a4cbb62]
/nix/store/bkg0g0g6adb6gam9yn6bdkigk8lp1mn5-csound-6.15.0/lib/csound/plugins64-6.0/librtalsa.so(+0x4722) [0x7f476a52f722]
/nix/store/bkg0g0g6adb6gam9yn6bdkigk8lp1mn5-csound-6.15.0/lib/libcsound64.so.6.0(+0x761dc) [0x7f476b3d71dc]
/nix/store/bkg0g0g6adb6gam9yn6bdkigk8lp1mn5-csound-6.15.0/lib/libcsound64.so.6.0(+0x49552) [0x7f476b3aa552]
/nix/store/bkg0g0g6adb6gam9yn6bdkigk8lp1mn5-csound-6.15.0/lib/libcsound64.so.6.0(csoundPerformKsmps+0x51) [0x7f476b3ac261]
./a.out() [0x401113]
/nix/store/gafigwfaimlziam6qhw1m8dz4h952g1n-glibc-2.32-35/lib/libc.so.6(__libc_start_main+0xed) [0x7f476b1c7ded]
./a.out() [0x40116a]
Csound tidy up: Interrupt
```

I realize now that thos could be related to alsa+pipewire, even more unrelated to this ticket
```
#0  0x00007ffff7bdb329 in poll ()
   from /nix/store/gafigwfaimlziam6qhw1m8dz4h952g1n-glibc-2.32-35/lib/libc.so.6
#1  0x00007ffff6dcdda5 in snd1_pcm_wait_nocheck ()
   from /nix/store/94ih212nc4nq8dy7vn03vzh9kk7znxk3-alsa-lib-1.2.4/lib/libasound.so.2
#2  0x00007ffff6dd30dd in snd1_pcm_write_areas ()
   from /nix/store/94ih212nc4nq8dy7vn03vzh9kk7znxk3-alsa-lib-1.2.4/lib/libasound.so.2
#3  0x00007ffff6ddf552 in snd_pcm_mmap_writei ()
   from /nix/store/94ih212nc4nq8dy7vn03vzh9kk7znxk3-alsa-lib-1.2.4/lib/libasound.so.2
#4  0x00007ffff6e15b62 in snd_pcm_ioplug_writei ()
   from /nix/store/94ih212nc4nq8dy7vn03vzh9kk7znxk3-alsa-lib-1.2.4/lib/libasound.so.2
#5  0x00007ffff6e79722 in rtplay_ ()
   from /nix/store/bkg0g0g6adb6gam9yn6bdkigk8lp1mn5-csound-6.15.0/lib/csound/plugins64-6.0/librtalsa.so
#6  0x00007ffff7d211dc in spoutsf ()
   from /nix/store/bkg0g0g6adb6gam9yn6bdkigk8lp1mn5-csound-6.15.0/lib/libcsound64.so.6.0
#7  0x00007ffff7cf4552 in kperf_nodebug ()
   from /nix/store/bkg0g0g6adb6gam9yn6bdkigk8lp1mn5-csound-6.15.0/lib/libcsound64.so.6.0
#8  0x00007ffff7cf6261 in csoundPerformKsmps ()
   from /nix/store/bkg0g0g6adb6gam9yn6bdkigk8lp1mn5-csound-6.15.0/lib/libcsound64.so.6.0
#9  0x0000000000401113 in main ()
```

So I'm closing this, since it doesn't exit anymore so it's fixed.
