### ISSUE TITLE
osx: cannot import csnd6 in system python 2.7 sound 6.15 

### ISSUE THREAD

**Issue by shakfu** [csound/csound#1430]
If one installs from the provide .dmg, Importing the python `csnd6` swig-generated external crashes in csound 6.15 on OS X Mojave: 

```bash
$ csound --version
0dBFS level = 32768.0
--Csound version 6.15 (double samples) Nov 20 2020
[commit: 18c2c7897425f462b9a7743cee157cb410c88198]
libsndfile-1.0.28
...
```

Here's the reproducible crash:

```python
Python 2.7.16 (default, Jan 27 2020, 04:46:15)
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import csnd6
dyld: warning, LC_RPATH @rpath/Library/Frameworks/CsoundLib64.framework/Versions/6.0/libcsnd6.6.0.dylib in /Library/Python/2.7/site-packages/_csnd6.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH @rpath/Library/Frameworks/CsoundLib64.framework/Versions/6.0/libcsnd6.6.0.dylib in /Library/Python/2.7/site-packages/_csnd6.so being ignored in restricted program because it is a relative path
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/csnd6.py", line 17, in <module>
    _csnd6 = swig_import_helper()
  File "/Library/Python/2.7/site-packages/csnd6.py", line 16, in swig_import_helper
    return importlib.import_module('_csnd6')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: dlopen(/Library/Python/2.7/site-packages/_csnd6.so, 2): Library not loaded: @rpath/libcsnd6.6.0.dylib
  Referenced from: /Library/Python/2.7/site-packages/_csnd6.so
  Reason: image not found
>>>
```

Looking at the link references for `_csnd6.so`:

```bash
$ otool -L /Library/Python/2.7/site-packages/_csnd6.so
/Library/Python/2.7/site-packages/_csnd6.so:
	@loader_path/../../../../../libs/libsndfile.1.dylib (compatibility version 2.0.0, current version 2.28.0)
	@rpath/libcsnd6.6.0.dylib (compatibility version 6.0.0, current version 0.0.0)
	@rpath/CsoundLib64.framework/Versions/6.0/CsoundLib64 (compatibility version 6.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```

**Comment by vlazzarini** [comment]
It's not a crash. It just can't find the library because of the rpath is not set. I can look to fix the installer so that it does not depend on the rpath. This can be done for 6.16.

However the csnd6 module is deprecated now. The best solution is to use the ctcsound module which also works on Python3.
