### ISSUE TITLE
crash with init error...

### ISSUE THREAD

**Issue by rorywalsh** [csound/csound#736]
The following code will caase an init time error when Csound is run from the command line. But when I call  Csound as a library I get a seg fault. 

```csound

instr 1000
kNoteIndex init 0
kNoteCnt init 0
if kNoteIndex==kNoteCnt == 0 then
	printks "Same", 0
endif
endin

```

Back trace is given here:

```
0  0x00007ffff678e5f0  csound_orcparse  /home/rory/sourcecode/cabbageaudio/csound/Engine/csound_orc.y  545
1  0x00007ffff67ac102  csoundParseOrc  /home/rory/sourcecode/cabbageaudio/csound/Engine/new_orc_parser.c  220
2  0x00007ffff67aa4a7  csoundCompileOrc  /home/rory/sourcecode/cabbageaudio/csound/Engine/csound_orc_compile.c  1778
3  0x00007ffff66afcfa  csoundCompileArgs  /home/rory/sourcecode/cabbageaudio/csound/Top/main.c  256
4  0x00007ffff66b0ae7  csoundCompile  /home/rory/sourcecode/cabbageaudio/csound/Top/main.c  512
5  0x0000000000442af6  Csound::Compile  /usr/local/include/csound/csound.hpp  217
```

**Comment by jpffitch** [comment]
⁣welcome back
Mail to ear.ie has been bouncing

**Comment by jpffitch** [comment]
Should give a syntax error⁣

**Comment by rorywalsh** [comment]
Does from the command line. But not when I call Csound through the API. Thanks for the heads up on my email. I had no idea.

**Comment by kunstmusik** [comment]
I am getting a crash on the commandline. With this CSD:

```csound-csd
<CsoundSynthesizer>
<CsOptions>
</CsOptions>
<CsInstruments>

instr 1000
  kNoteIndex init 0
  kNoteCnt init 0
  if kNoteIndex==kNoteCnt == 0 then
    printks "Same", 0
  endif
endin
</CsInstruments>
<CsScore>
i1000 0 0.1 
</CsScore>
</CsoundSynthesizer>
```

I get this in GDB:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000006c686190 in csound_orcparse (parm=parm@entry=0x66f350,
    scanner=<optimized out>, csound=csound@entry=0x2550080,
    astTree=astTree@entry=0x66ef50)
    at C:/msys64/home/stevenyi/work/csound/csound/Engine/csound_orc.y:546
546                       $$ = make_node(csound,$2->line, $2->locn, IF_TOKEN, $2, $3);
(gdb) bt
#0  0x000000006c686190 in csound_orcparse (parm=parm@entry=0x66f350,
    scanner=<optimized out>, csound=csound@entry=0x2550080,
    astTree=astTree@entry=0x66ef50)
    at C:/msys64/home/stevenyi/work/csound/csound/Engine/csound_orc.y:546
#1  0x000000006c696237 in csoundParseOrc (csound=0x2550080,
    csound@entry=0x27e81c0,
    str=str@entry=0x7ffe42d77dc0 <msvcrt!_sys_errlist+10368> "\001")
    at C:/msys64/home/stevenyi/work/csound/csound/Engine/new_orc_parser.c:220
#2  0x000000006c695d83 in csoundCompileOrc (csound=0x27e81c0,
    csound@entry=0x405108,
    str=0x7ffe42d77dc0 <msvcrt!_sys_errlist+10368> "\001", str@entry=0x0)
    at C:/msys64/home/stevenyi/work/csound/csound/Engine/csound_orc_compile.c:1794
#3  0x000000006c5fc8d8 in csoundCompileArgs (csound=0x405108,
    csound@entry=0x2550080, argc=4215048, argc@entry=2,
    argv=0x403100 <main+384>, argv@entry=0xf326b0)
    at C:/msys64/home/stevenyi/work/csound/csound/Top/main.c:256
#4  0x000000006c5fd6ad in csoundCompile (csound=csound@entry=0x2550080,
    argc=argc@entry=2, argv=argv@entry=0xf326b0)
    at C:/msys64/home/stevenyi/work/csound/csound/Top/main.c:509
#5  0x0000000000403100 in main (argc=2, argv=0xf326b0)
    at C:/msys64/home/stevenyi/work/csound/csound/frontends/csound/csound_main.c:316
```

**Comment by jpffitch** [comment]
Fixed in git

**Comment by kunstmusik** [comment]
@rorywalsh I'm wondering if @jpffitch 's fix affects usage from API. Could you retest with latest?

**Comment by rorywalsh** [comment]
Will do, but it won't be until tomorrow.

**Comment by rorywalsh** [comment]
No problems here using the API. Note I tested on Linux. I won't have time to test on Windows for a day or two.

**Comment by kunstmusik** [comment]
@rorywalsh Is this issue fixed for you on Windows?  If so, we'd like to close this ticket.
